### ISSUE TITLE
Loading the gem errors out with `uninitialized constant SunshineConversationsClient::CustomUpdateAllOf (NameError)` error

### ISSUE THREAD

**Issue by sarojkh** [zendesk/sunshine-conversations-ruby#27]
Encountered on: 
- Ruby `3.2.2`
- Rails `7.0.8.1`

The backtrace:
```
$> bin/rails console                                                                                                                                                                                                      [ 3.2.2 ]
/Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sunshine-conversations-client-12.6.2/lib/sunshine-conversations-client/models/custom_update.rb:13:in `<module:SunshineConversationsClient>': uninitialized constant SunshineConversationsClient::CustomUpdateAllOf (NameError)

  class CustomUpdate < CustomUpdateAllOf
                       ^^^^^^^^^^^^^^^^^
Did you mean?  SunshineConversationsClient::CustomAllOf
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sunshine-conversations-client-12.6.2/lib/sunshine-conversations-client/models/custom_update.rb:12:in `<main>'
	from <internal:/Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sunshine-conversations-client-12.6.2/lib/sunshine-conversations-client.rb:131:in `<main>'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:60:in `require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:55:in `each'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:44:in `each'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:44:in `require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler.rb:187:in `require'
	from /Users/sarojk/git/somefolder/config/application.rb:19:in `<main>'
	from <internal:/Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8.1/lib/rails/command/actions.rb:22:in `require_application!'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8.1/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8.1/lib/rails/commands/console/console_command.rb:105:in `perform'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8.1/lib/rails/command/base.rb:87:in `perform'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8.1/lib/rails/command.rb:48:in `invoke'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8.1/lib/rails/commands.rb:18:in `<main>'
	from <internal:/Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/sarojk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by sarojkh** [comment]
This apparently fixed it for me. https://github.com/sarojkh/sunshine-conversations-ruby/pull/1
